[project]
name = "midi-gen"
version = "0.1.1"
dependencies = [
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "pydantic>=2.8.0",
    "python-dotenv>=1.0.1",
    "pianogen @ git+https://github.com/eri24816/piano-music-gen.git"

]

[tool.hatch.metadata]
allow-direct-references = true